#!/bin/bash
if [ ! -d venv ]; then
    virtualenv venv;
fi;

. venv/bin/activate

if [ ! -d pyCraft ]; then
    git clone git@github.com:ammaraskar/pyCraft.git;
fi;

cd pyCraft
python setup.py install
cd ..

pip install -r requirements.txt
